title: Princeton Poh
description: "Entrepreneur, builder, and engineer based in Singapore."
baseurl: ""
url: "https://princetonpoh.github.io"

author:
  name: Princeton Poh
  email: niceprinceton@gmail.com
  github: PrincetonPoh
  linkedin: princeton-poh

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /blog/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

kramdown:
  hard_wrap: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
  - "*.log"
